### ISSUE TITLE
[BUG] Ergast API returns Status Code 403 (original: "ff1.get_session returns TypeError")

### ISSUE THREAD

**Issue by NavjotSaroa** [theOehrly/Fast-F1#102]
### Describe the issue:

I ran the code on the getting started page (https://theoehrly.github.io/Fast-F1/examples/index.html?highlight=monza_quali) that would display the telemetry graph, but got "TypeError: 'NoneType' object is not subscriptable"

### Reproduce the code example:

```python
from matplotlib import pyplot as plt
import fastf1 as ff1
from fastf1 import plotting

plotting.setup_mpl()

monza_quali = ff1.get_session(2019, 'Monza', 'Q')

laps = monza_quali.load_laps(with_telemetry=True)
fast_leclerc = laps.pick_driver('LEC').pick_fastest()
lec_car_data = fast_leclerc.get_car_data()
t = lec_car_data['Time']
vCar = lec_car_data['Speed']

# The rest is just plotting
fig, ax = plt.subplots()
ax.plot(t, vCar, label='Fast')
ax.set_xlabel('Time')
ax.set_ylabel('Speed [Km/h]')
ax.set_title('Leclerc is')
ax.legend()
plt.show()
```

### Error message:

```shell
Exception has occurred: TypeError
'NoneType' object is not subscriptable
  File "C:\Users\navjo\Desktop\tester.py", line 9, in <module>
    monza_quali = ff1.get_session(2019, 'Monza', 'Q')

UserWarning: Request returned: 403
  warnings.warn(f"Request returned: {r.status_code}")
```

**Comment by theOehrly** [comment]
The TypeError is the consequence of a previous error. The warning which is printed below it shows the actual root cause. 
HTTP Status Code 403 is 'Forbidden', i.e. the server has rejected the request. 
I'm currently not encountering that issue, so it was either a temporary problem or it is something specific to your environment. Please just wait for a bit and then try again. If it still doesn't work after some time, then we need to investigate, why this happens for you.

**Comment by NavjotSaroa** [comment]
Hi! It has been about 12 hours now, I ran the code and it worked just fine. Thank you for your help!

**Comment by theOehrly** [comment]
Awesome, good to hear. Looks like it was just a temporary connection error or server error then.
