### ISSUE TITLE
F1 is breaking this on purpose, and they are probably right

### ISSUE THREAD

**Issue by pallo125** [theOehrly/Fast-F1#11]
Hello,
I hope my words are not taken badly, but I would like to suggest to put a sort of login procedure at the beginning of the connection which will allow only those who have a subscription to the f1 account to access the data. The F1 app is a paying app and by using this script you are allowing anyone, even those who do not have a subscription, to access the data. This was probably discovered and now F1 is removing the files on purpose, since it is removing just the data files this script basically use. So, if I may suggest, I would reconsider the policy of this app because the more you push for letting the data free of paying, the more F1 will make it difficult to get them and since the rest of the public are paying to see the numbers I personally believe they are right.

Regards
P

**Comment by theOehrly** [comment]
Hi, I have to disagree with you on multiple points there. First, I highly doubt that this is done on purpose and it is certainly not done because of this project. F1 is not going to shoot themselves in the foot by partially breaking their own app because of some semi-stable code on github and a few lonely users. There are multiple better ways to prevent third parties from accessing the data. Additionally, only parts of the data are no longer available. If you do the API calls manually, you can still load timing data for example. The convenience function for loading all data crashes because it tries to load all data and can't handle data being only partially available.
The argument, that this data should only be available to people who pay for access can certainly be made. One can debate whether customers are paying for the data or the nice app interface, visualization, and so on though. But whatever anyone's opinion on this is, it currently doesn't matter. The live timing API doesn't want a user to authenticate. I simply cannot authenticate a user against an API that doesn't want authentication. It's not possible. So there's that.
Furthermore, this project is in no way in competition with the official app. And there is no intention of competing with the features which the app offers. This python module offers functionality that is not available in the official app. 
Therefore, I think there is nothing that can and should be done here.

**Comment by WolfastGuzmanLopez** [comment]
Hello theOehrly,

Would you mind expanding on the topic of manually calling the API to obtain time data and prevent the API from crashing due to telemetry data been inaccessible? I'm interested in obtaining lap times for each session and driver to build some kind of pace analyzer.

Thank you very much in advice, you should charge more than F1 for the work you do hahahaha
Best regards

Guzmán

**Comment by theOehrly** [comment]
The next version of the module separates loading of telemetry data and timing data. While by default both will be loaded it'll be easy to load only telemetry data. 
You should expect a release (or at least a pre-release of the next version within this week).
But which data is or isn't available will be seen. I, of course, have no idea what F1 are doing with their API.

**Comment by WolfastGuzmanLopez** [comment]
That would be awesome. Thank you so much and let's hope that F1 gets their stuff together and fixes the API.

Thanks again,
Regards

Guzmán

**Comment by theOehrly** [comment]
The pre-release is available now. Use the new argument `with_telemetry=False` when calling `Session.load_laps` to load only timing data.

**Comment by WolfastGuzmanLopez** [comment]
That's awesome! Thank you so much again theOehrly, now it works fine when trying to download lap data!
