### ISSUE TITLE
[BUG] Ergast fetch_weekend() resulting in KeyError: 'elevation' for certain races

### ISSUE THREAD

**Issue by renville-colin** [theOehrly/Fast-F1#119]
### Describe the issue:

Hello! As of 3/17, I have been getting a Keyerror resulting from using the fetch_weekend() function on certain races.
Weirdly, the races that are problems have been different on different days. 

Summary
3/16: no issues
3/17: keyerror listed below for races 4 (Spain) and 13 (Netherlands)
3/18: keyerror listed below for races 6 (Azerbaijan) and 13 (Netherlands) 

These races weren't giving me any issues previously. Hate that I can't get a totally stable, reproducible example for you on this, but it seems like the altitude / elevation data seems to be behaving oddly so I figured I would throw it your way. 

### Reproduce the code example:

```python
import fastf1 as ff1

# works
test_weekend1 = ff1.core.ergast.fetch_weekend('2021', 3)

# keyerror for Baku and Netherlands
test_weekend2 = ff1.core.ergast.fetch_weekend('2021', 6)
test_weekend3 = ff1.core.ergast.fetch_weekend('2021', 13)
```

### Error message:

```shell
KeyError: 'elevation'
```

**Comment by theOehrly** [comment]
It's caused by a server-side error  on the api requests that fetches the elevation data. The API used for that is quite sketchy, therefore, if this doesn't resolve itself, I have to look for a replacement.

This won't get priority as that functionality is completely undocumented and since the release of v2.2 `.fetch_weekend` is not even used internally any more. I might bring circuit information with coordinates and elevation back though.
