### ISSUE TITLE
[BUG] Loading telemetry for all the laps of a driver

### ISSUE THREAD

**Issue by feDann** [theOehrly/Fast-F1#143]
### Describe the issue:

Hello! When i try to retrieve the telemetry data for all the laps of a driver the Distance column is shared between all the laps , this means that the value of Distance ranges between 0 and 90k (2022 Bahrain Q). I don't know if i'm using the function in a wrong way but just to be sure i decided to open the issue. This is a screenshot of the tail of the telemetry df 
![Immagine 2022-04-03 195337](https://user-images.githubusercontent.com/33935699/161441462-c9ec8ac5-3c23-4857-b395-44da38ad77fd.png)

### Reproduce the code example:

```python
session = ff1.get_session(2022, "Bahrain" , "Q")
session.load()
driver_laps= session.laps.pick_driver("HAM")
telemetry = driver_laps.get_telemetry()
```

**Comment by markste-in** [comment]
You need to iter over every lap:
See example (same for get_telemetry):
```
for driver_lap in event.laps.pick_driver(driver).iterlaps():
    driver_tel = driver_lap[1].get_car_data()
```

**Comment by theOehrly** [comment]
This is intentional and not a bug. The methods of the `Telemetry` class operate on the current `Telemetry` object, and telemetry data itself is independent of lap data. You can slice telemetry data using lap data (which is also done when you call `Lap.get_telemetry` and similar methods). But you can also create arbitrary slices of telemetry data.

The solution to your problem is what @markste-in commented above.
