### ISSUE TITLE
LapTime bug

### ISSUE THREAD

**Issue by Atishay1712** [theOehrly/Fast-F1#167]
For the 2022 Saudi Arabian GP Qualifying there is a lap by Max Verstappen(lap12) which has a LapTime of 1:01 instead of NaT, which is the sum of the sector 2&3 lap times. This lap has a track status - 5. Maybe it is due to this the bug is arising.  Due to this, the pick_quicklaps() is not working properly.
Thanks

**Comment by theOehrly** [comment]
The problem is not caused by FastF1 directly. The source data is actually wrong here and actually contains the 1:01 lap time. This of course is somehow related to this being the first lap after the red flag. This really is a normal outlap after the session was resumed. There shouldn't be anything special about it. I need to see if I can detect and auto-fix this problem.

The track status for this lap is incorrect and only set because the lap start time is wrong too.
