### ISSUE TITLE
[BUG] Monaco GP qualifying: ValueError when calling .get_telemetry()

### ISSUE THREAD

**Issue by japserboy** [theOehrly/Fast-F1#182]
### Describe the issue:

With the Monaco GP qualifying, Fastf1 throws a ValueError when calling `get_telemetry()`, while FP1/FP2 were working just fine. I'm not sure what causes the issue - it appears to be coming from the calculation of the driver ahead in `Fastf1.core`.

It works just fine when calling `get_car_data()`.

### Reproduce the code example:

```python
session = ff1.get_session(2022, 'Monaco', 'Q')
session.load()

laps_ver = session.laps.pick_driver('VER').pick_fastest()
laps_ver.get_telemetry().add_distance()

# ^ The code above only doesn't work when calling get_telemetry(). get_car_data() works just fine
```

### Error message:

```shell
ValueError: columns overlap but no suffix specified: Index(['14'], dtype='object')
```

**Comment by theOehrly** [comment]
This is ultimately caused because Ergast lists Alonso twice in the Qualifying results. Therefore, `Session.drivers` contained his car number twice, which caused problems subsequently. 
I've now ensured that the driver list does not contain duplicate entries, which fixes the problem reported by you.
You can go ahead and update FastF1 and everything should be working then.

The session results will still be partially wrong, because the source data is wrong. I've forwarded this issue to the Ergast Admin. So it will likely get corrected fairly soon.

**Comment by theOehrly** [comment]
The source data has now been updated as well on Ergast. So everything is working as it should now and the correct data is shown.
