### ISSUE TITLE
[Info] Auto insertion of turns and sectors labels

### ISSUE THREAD

**Issue by nicZox** [theOehrly/Fast-F1#19]
Hi, is it possible to implement a system that, based on the GPS tracks, inserts labels in the X axis of the Distance with the number of the turn and the sectors?

**Comment by theOehrly** [comment]
The sector times are really only a bit of pandas/numpy math. Not sure if and how I will add something like this into the package. You can do it like this (when plotting over distance):

    dt, ref_tel, compare_tel = ff1.utils.delta_time(ref_lap, comp_lap)

    sec12 = ref_tel['Distance'].iloc[np.argmin(abs(ref_tel['SessionTime'] - ref_lap['Sector1SessionTime']))]
    sec23 = ref_tel['Distance'].iloc[np.argmin(abs(ref_tel['SessionTime'] - ref_lap['Sector2SessionTime']))]
    plt.vlines(sec12, min(dt), max(dt), colors='yellow')
    plt.vlines(sec23, min(dt), max(dt), colors='yellow')

Basically, find the index of the row where the time is closest to the sector session time and get the distance at this index.
Of course, when plotting over time, it is even easier.

Numbering the corners is a very different beast  though. There are a LOT of problems with that. Starting with what even is and isn't considered a corner. There is no useful data on that, as far as I know. I don't know how to even get the total number of corners. Furthermore, recognizing corners reliably from position data is not trivial either. I don't know if this will ever be possible. I certainly don't have time for something like this currently.

**Comment by ukaoskid** [comment]
@theOehrly I have found this repo which is collecting geolocalized data of the circuits https://github.com/bacinger/f1-circuits.
Anyway, I think the only reliable way of doing that is to try to find (or calculate from the repo I have found, which is what I am doing) at what distance is each turn so that it can be inferred to the distance field in the dataframe.

**Comment by theOehrly** [comment]
@ukaoskid interesting data that you found there. What I do not understand, if you can calculate the corner locations from that data, why can't you do the same with the position data in FastF1? After all it should more or less just be scaled and rotated coordinates, no?

**Comment by ukaoskid** [comment]
I think it's hard to calculate corners, actually, we should start also by defining what is and what it's not a corner, it's very hard to automate this task. I rather think that it's easier to mark geographically (coordinates) the center of each turn visually, and then calculate de distance from one marker to the other so that you have the relative distance. The absolute distance is the progressive summation of each segment. This, actually, can be ran one time and will generate a master data useful to be added to the lib.

I am already building this database and I would be happy to share it with you, if you think it is a good idea.

**Comment by theOehrly** [comment]
@ukaoskid That would be really nice to have. The question of automatically labelling turns has come up a few times already. It would be nice to include this, for sure. This is a cool idea and likely the only one that will work properly. How do you plan to make this data available?

**Comment by theOehrly** [comment]
JSON or some API is fine. I guess there are plenty of options. I don't have anything that I'd specifically prefer here. It'd be good if the server supports http cache control headers if it is something like downloading a JSON file, so that the number of requests can be reduced.
I think it would also be great if the data can be accessed without FastF1 as well. There's nothing equivalent currently, so you should probably try to make it as open and easily available as possible.

One question regarding the above graph, why are (some/all?) corners marked before the braking zone even starts? Is this intentional or is this an accuracy problem still.

**Comment by ukaoskid** [comment]
@theOehrly yeah, I will try to male it as open as possible and most likely JSON.

Regarding the graph, yes, it is on purpose and nothing regarding the acciracy, as the grometry I have have lots of points, so resplution-wise is pretty much accurate. I am still adjusting the   "turns editor" in order to map them properly

**Comment by ukaoskid** [comment]
@theOehrly I have a very good accuracy right now
![image](https://user-images.githubusercontent.com/11193544/174483325-072e3ed7-ad38-4128-9a01-504427276367.png)

The plan, actually, is to release a first version which is only containing an array of turns with just the relative and the absolute distance, like:

```typescript
{
  turns: [
    { 
       number: number; // 1
       description: string; // turn name
       distance: {
         relative: number;
         absolute: number;
       }
    }
  ]
}
```
The payload will contain a `turn zero` that identifies the start line.

In a second version I will be also adding a `position` object which will contain exactly the geographical position

**Comment by TheCommishDeuce** [comment]
@ukaoskid are there any updates on this? Hopefully, it's going well, looking forward to the first release.

**Comment by ukaoskid** [comment]
Hey  @TheCommishDeuce it won't take much more time, I am next to finish.
It takes a bit to tune to the exact distance each turn so that it looks correct on the telemetry

**Comment by ukaoskid** [comment]
@theOehrly @TheCommishDeuce I have added a first tranche of circuits, just a bunch for you guys to see if it's OK like that before continuing giving the format to the data. Can you guys provide feedback?

[](https://github.com/ukaoskid/f1-circuits-data)

**Comment by TheCommishDeuce** [comment]
@ukaoskid seems good to me, easily integrated into my telemetry workflow but the real question is whether you gather the information needed by hand? Surely it's going to take a long time doing it this way but of course I couldn't manage the alternative myself)

**Comment by ukaoskid** [comment]
@TheCommishDeuce the only way is to map turns manually, of course. I adjust them on the telemetry to make sure the entry points are correct to the meter. It's not much job, though. I have most of the circuits mapped, but not formatted yet on the interface that I have provided in the repository. What I am doing now is formatting the array of distances that I have already mapped

**Comment by TheCommishDeuce** [comment]
Appreciate your work, my gf has been bugging me with the lack of turn references for weeks at this point. Really glad I have found this and looking forward for @theOehrly to maybe integrate your arrays into the mainline repo soon.

**Comment by ukaoskid** [comment]
Anytime, happy to be useful to this world.
I am planning to release all the 2022 circuits (read the [README.md](https://github.com/ukaoskid/f1-circuits-data/blob/main/README.md)) by the end of next week.
