### ISSUE TITLE
[ENH] Expose logging configuration options

### ISSUE THREAD

**Issue by 0xMetas** [theOehrly/Fast-F1#211]
### Proposed new feature or change:

There doesn't seem to be a way to disable output from commands like `Session.load()` or redirect the logger output without additional Python code outside of the library. A new set of utility functions may improve the UX when dealing with this output. Something like:

```python
Logging.level(...)
Logging.set_logger(...)
Logging.get_logger()
```

Additionally, a new argument to `Session.load()` will make it even easier for users not familiar with the logger:
```python
def load(self, *, laps=True, telemetry=True, weather=True, messages=True,
             livedata=None, quiet=False):
```
where `quiet=True` will disable all logs to standard output for that invocation.

**Comment by theOehrly** [comment]
I fully agree that this should be improved at some point. I have thought about this before, But I do not really consider it an urgent problem, that's why it was pushed back multiple times already.

FastF1 uses the built-in python logging module. Therefore, even with the current crude implementation, you have some control. You can for example silence warnings fairly easily by setting the logging level of the root logger.
```
import logging

import fastf1

logger = logging.getLogger()
logger.setLevel(logging.WARNING)

session = fastf1.get_session(2022, 'Canada', 'R')
session.load()
```

I agree that there should be an explicit interface to control how logging works, as well as some simple things like the `quite=True` argument that you proposed.

Generally, I am open to proposals on how to improve this. Pull requests are welcome too.

**Comment by 0xMetas** [comment]
I can work on a PR for this. I'll start off with the API I proposed but I'm open to changes.

**Comment by theOehrly** [comment]
We probably need to drop the simple ``logging.basicConfig(...)`` call in ``fastf1.core``. I suppose it will be necessary to create an actual logger object so that the logging behaviour can be adjusted more specifically for FastF1 only. For example, the example I gave above for silencing some messages directly modifies the root logger configuration. As a consequence, you may suddenly also see logging messages from modules like request-cache, depending on what logging parameters you adjust. This should not happen.
Additionally, it might be nice if logging levels can be configured per submodule. Mainly for development and debugging purposes, it would be helpful if we can for example set the logging level for ``fastf1.api`` to DEBUG, but keep other modules at INFO.
