### ISSUE TITLE
[ENH] Implementing standings for drivers and constructors

### ISSUE THREAD

**Issue by oscr** [theOehrly/Fast-F1#229]
### Proposed new feature or change:

I think it would be useful to be able to get constructor and driver standings with fastf1. I have therefore started working on a draft which gets its data from Ergast: http://ergast.com/mrd/methods/standings/

I suggest adding a new module `standings` with the following functions initially 

```python
get_driver_standings(year, round="optional") 
get_constructor_standings(year, round="optional")
```

This can later be expanded with getting historic standings for a specific driver etc. 

Is this something that would be useful?

**Comment by theOehrly** [comment]
Yes, support for Ergast needs to be improved in general. I had also been thinking about adding full support for all data that Ergast provides in some unified way. After all, the API is quite easy to work with. I haven't really thought about any details yet, though. Also, I'm not sure yet how necessary and helpful that really is. 
But I am a bit annoyed that if support for the F1 API breaks, there is no way to get even just lap times, even though Ergast provides them as well. 

So back to your main question, yes this would be useful. We just need to figure out, whether we want to add this as a standalone new feature or in combination with better support for Ergast in general. What is your opinion on that?

**Comment by oscr** [comment]
When you say in a unified way what do you have in mind?

Overall I see advantages of having fastf1 as a complete wrapper for the Ergast api. It offers caching out of the box, simpler access to the data (especially for beginners), it enables easy discoverability and in combination with f1 data it's very powerful.

My personal usage right now goal is to write a small scripts like "who can still win the wdc" etc. So I of course think more Ergast is helpful :)

**Comment by theOehrly** [comment]
What I mean is that the structure of all API calls for Ergast is very similar and so is the returned data. So what I (very loosely) have in mind is that this structure is represented in the python implementation as well. This should make it easy to work with and as self-explanatory as possible. As in, for example, you have matching call signatures for standings and results, and you get back the data in the same format.
IMO, it is likely best to return all results as dataframes. First, because I think they are very nice to work with for that kind of data and because "everything-is-a-dataframe" is kind of the concept behind FastF1.
In terms of implementation, it should be possible to handle all API endpoints with mostly the same code, instead of implementing them all completely separately. This should lead to easy maintenance and testing. 

This is still not overly specific, I know. But as I said, I hadn't really thought about any details yet.

There also is https://github.com/Samuel-Roach/ergast-py which we should take a look at before implementing anything from scratch here.

**Comment by oscr** [comment]
I think that sounds like a great approach given how flexible the dataframes are. In general getting more data, caching it and then using the dataframes to filter out what you want could simplify the api access patterns a lot.

**Comment by theOehrly** [comment]
I'll close this now that #311 is merged.
