### ISSUE TITLE
[ENH] Makefile

### ISSUE THREAD

**Issue by oscr** [theOehrly/Fast-F1#255]
### Proposed new feature or change:

I would like to add a `Makefile` with some common targets to improve developer experience. For example:

- `lint`
- `test`
- any other complex command.

No one is forced to use the Makefile because anyone can still run the full commands. But from a developer experience it's just so much easier to run `make lint` instead of `git diff origin/master -U0 --relative | flake8 --max-line-length 79 --diff --select E501 fastf1 examples scripts`.

**Comment by theOehrly** [comment]
Potentially it is sufficient to add an overview over all commands in the documentation. We currently have the following short commands:

- `pytest` for running tests.

- `pytest --f1-tel-api` for running all tests including those that require api access

- `python setup.py build_sphinx` to build the documentation

- `flake8 fastf1` for lint without line length


Also, there are pre-commit hooks available to be installed for lint + line length validation of the diff, so that in theory lint should never fail in CI.

You can also run the pre-commit hooks manually with `pre-commit run`

And in theory, you can run `python scripts/flake8_line_length.py` to run the line length validation of the diff as well.

Of course, one could use a makefile to shorten these commands even more.

**Comment by oscr** [comment]
What I really like about Makefiles is that regardless of what project and language used I can simply run `make` and get a list of commands (with some minor makefile hacking). The common targets such as `lint`, `test` always work and I don't need to lookup anything. I would prefer the line length to be found locally instead of having to update the pr. This would make less noise for you also as a reviewer. I know that I've pushed a few times extra to fix flake8s findings.

**Comment by theOehrly** [comment]
Sure, if you like, go ahead and create a makefile for that. Make is not really something I use a lot. Currently my main os for development is still Windows. And make doesn't really work there.
I see the advantage though and it doesn't hurt to have it, that's for sure.
