### ISSUE TITLE
[BUG] .gitignore does not ignore python venv folders

### ISSUE THREAD

**Issue by ndv99** [theOehrly/Fast-F1#261]
### Describe the issue:

Upon cloning the repository and setting up a virtual environment in Python, the new folders are tracked in the repository, which they should not be.

I propose adding the following lines to .gitignore:

```gitignore
.Python
[Bb]in
[Ii]nclude
[Ll]ib
[Ll]ib64
[Ll]ocal
[Ss]cripts
pyvenv.cfg
.venv
pip-selfcheck.json
```

### Reproduce the code example:

In the directory above `Fast-F1`:
```bash
python3 -m venv Fast-F1
```

### Error message:

![image](https://user-images.githubusercontent.com/35104482/192253689-726db27c-c542-4841-bab2-c0099a0361c5.png)

**Comment by theOehrly** [comment]
The problem here is that you use the project root directory as the folder where you create the venv. You should use an empty (!) folder. This folder should preferably be outside the project directory. As an alternative, you can use a folder that is named venv (which is excluded by .gitignore) inside the project root. But you should never create a venv inside a folder that is used for anything else.

**Comment by theOehrly** [comment]
Actually, if you place a venv inside a project directory you more commonly would name the subfolder `.venv`.
Still, you should really prefer to place them outside as placing them inside the project directory really starts cluttering up stuff, when you start to have multiple environments.

**Comment by nottrobin** [comment]
I appreciate that you don't want to pollute your `.gitignore` for different local development styles, given that these can vary significantly. Not least because the virtualenv folder could be named various things (although apparently `venv` is the recommendation - see below). It totally makes sense and this decision seems entirely justified.

I'd just like to point out that keeping the virtualenv folder inside the project folder is probably a lot more common than you realise. As an open source project, I imagine many more members of your community are doing this than you might think. We can see evidence of this in various places:

https://docs.python-guide.org/dev/virtualenvs/#basic-usage

> Create a virtual environment for a project:
> 
> ```
> $ cd project_folder
> $ virtualenv venv
> ```
> 
> virtualenv venv will create a folder in the current directory which will contain the Python executable files, and a copy of the pip library which you can use to install other packages. The name of the virtual environment (in this case, it was venv) can be anything; omitting the name will place the files in the current directory instead.
> 
> Note
> ‘venv’ is the general convention used globally. As it is readily available in ignore files (eg: .gitignore’)

https://code.visualstudio.com/docs/python/environments

> The extension automatically looks for interpreters in the following locations:
> 
> - Standard install paths such as /usr/local/bin, /usr/sbin, /sbin, c:\\python27, c:\\python36, etc.
> - Virtual environments located directly under the workspace (project) folder.

https://stackoverflow.com/questions/40332383/where-do-i-store-my-python-program-files-when-using-a-virtual-environment

> However, most projects put the environment right next to their source code within their project folder

But as I say it's totally fair to want to  keep your `.gitignore` file clean.

**Comment by theOehrly** [comment]
@nottrobin I agree that this is fairly common and I do this myself for some projects. But this was not the issue here. The fairly common  `venv` folder is already added in `.gitignore` to allow this.
