### ISSUE TITLE
[BUG] Autocomplete error message for event

### ISSUE THREAD

**Issue by oscr** [theOehrly/Fast-F1#273]
### Describe the issue:

I noticed an interesting error when trying to autocomplete `event` the first time. After pressing tab twice there is an error message and the autocomplete seems to be stuck so you have to press ctrl+c to escape. The second time it works as expected. Other objects such as `session` doesn't show this behavior.

Full output
```
python3
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastf1
>>> event = fastf1.get_event(2021, 1)
api         WARNING 	

DEFAULT CACHE ENABLED!
	Cache directory: /home/oscar/.cache/fastf1.
	Size: 7.63 MB
>>> event./home/oscar/repo/github/fast-f1/fastf1/events.py:676: FutureWarning: The `Weekend.name` property is deprecated and will beremoved in a future version.
Use `Event['EventName']` or `Event.EventName` instead.
  warnings.warn(
```

### Reproduce the code example:

```python
$ python3
>>> import fastf1
>>> event = fastf1.get_event(2021, 1)
>>> event.<<NOW PRESS TAB TWICE>>

<<HAVE TO PRESS CTRL+C TO ESCAPE>>
```
```


### Error message:

```shell
/home/oscar/repo/github/fast-f1/fastf1/events.py:676: FutureWarning: The `Weekend.name` property is deprecated and will beremoved in a future version.
Use `Event['EventName']` or `Event.EventName` instead.
  warnings.warn(
```

**Comment by theOehrly** [comment]
There's a very hacky workaround in the event class to show that future warning. The problem is that the old Weekend class was replaced with the new Event class, which is based on a pandas Series. The weekend class had a `.name` attribute but pandas Series objects have an internal `.name` attribute. So these two collided. 
Currently, access to the pandas internal `.name` attribute is prevented to provide backwards compatibility and the future warning is shown. But this only becomes active after the object is fully initialized. Before that, the internal `.name` attribute is accessible because some internal stuff in pandas would otherwise fail. 
This very convoluted way of doing things seems to cause some kind of problem here.

I could have dropped backwards compatibility in the 2.3.0 release already, but that would have meant a very short deprecation period. As I didn't know of any issues at that point, I decided to give some more time. 
Currently, I'm planning to drop backwards compatibility with the 3.0.0 release. That should fix this problem.
