### ISSUE TITLE
[ENH] Add function for adding track status data to telemetry

### ISSUE THREAD

**Issue by theOehrly** [theOehrly/Fast-F1#296]
### Proposed new feature or change:

Track status data is currently only available as a separate data object (`Session.track_status`). It is not possible to easily visualize at which point during a lap the track status changed to yellow flag for example.

Proposal: Add the function `Telemetry.add_track_status` which uses the already available track status information to and add the current status to each telemetry sample.

**Comment by SpyrosKoun** [comment]
Hi,

I would like to contribute to Fast-F1. I believe this issue is a good starting point and I’d like to give it a try. Do you have any more specifications?

**Comment by theOehrly** [comment]
Hi @SpyrosKoun, yes, I do believe that this issue should be a good starting point for contributing to FastF1.

When I just looked at this again, I noted that there is one additional small thing that needs to be done first. The track status data is currently not available as a property of the Session object. The data is loaded in `Session.load` and used to set the track status for each lap. But the original data is then not saved as a property of `Session`. Basically, create a DataFrame `Session._track_status` and a property `Session.track_status` to access it. This should be an exact copy of what is done for session status data. Therefore, it should be fairly simple to do, and it barely involves any code changes. You could even do this as a simple first pull request if you like.

After that, for the Telemetry object, you'll add a method `add_track_status`. When this method is called, it gets the track status data from the new object that you just created (through `Telemetry.session.track_status`). The track status data will contain an event every time the track status changes. So for each event in the track status data, all telemetry samples after that event and until the next event will get this track status value.
Here, it is important to keep efficiency in mind. The telemetry object/dataframe contains many samples. Therefore, one thing you can absolutely not do, for example, is to loop over all samples and look up their status in the track status data. You need to make use of pandas indexing or other pandas functionality to set these values efficiently. Some potential options:
- loop over the track status data and set all the values in between two events at once, using pandas indexing
- use something like DataFrame.apply (not sure how fast that would be)
- merge the track status data and telemetry on time and do a forward fill
There's probably more ways to make this work. I just wanted to give you some ideas.

In general, make sure to read https://theoehrly.github.io/Fast-F1/contributing/index.html before you get started. You'll have it much easier, if you properly set up your development environment.

If you have any more questions, feel free to ask.

**Comment by SpyrosKoun** [comment]
When calling the `Session.laps.get_telemtry()` method I get back an instance of `Telemetry`, where the index starts from the number 2 (I figured because of the padding used). Is this a feature or a bug? When I try to join the new `TrackStatus` column I get unexpected results because of the different indexing. 

Showcasing an example: 

I try to join the already existing `Telemetry` object (shape [32562, 18]) and the new `TrackStatus` column (shape [32562, 1]), but instead of a new object of shape [32562, 19], I get an object of shape [32564, 19]. Using the `DataFrame.reset_index()` method on the already existing `Telemetry` object solves the issue, but I dont know if this is supposed to be a feature or not.

`
                         Date            SessionTime  ...      Z  TrackStatus
0                         NaT                    NaT  ...    NaN     AllClear
1                         NaT                    NaT  ...    NaN     AllClear
2     2022-06-11 14:15:56.771 0 days 00:30:56.762000  ...    0.0     AllClear
3     2022-06-11 14:15:56.871 0 days 00:30:56.862000  ...    0.0     AllClear
4     2022-06-11 14:15:57.017 0 days 00:30:57.008000  ...    0.0     AllClear
...                       ...                    ...  ...    ...          ...
32559 2022-06-11 15:27:35.283 0 days 01:42:35.274000  ... -244.0       Yellow
32560 2022-06-11 15:27:35.364 0 days 01:42:35.355000  ... -243.0       Yellow
32561 2022-06-11 15:27:35.524 0 days 01:42:35.515000  ... -244.0       Yellow
32562 2022-06-11 15:27:35.583 0 days 01:42:35.574000  ... -244.0          NaN
32563 2022-06-11 15:27:35.618 0 days 01:42:35.609000  ... -243.0          NaN

[32564 rows x 19 columns]
`

**Comment by theOehrly** [comment]
Are you creating the new TrackStatus column from the original full length data? Or why does it have more rows? My idea was to just use the existing data within the telemetry object as a source. 
Also, in my opinion, it would be better not to rely on the index as it is easily changed. All merging and aligning of data is better done based on date or session time.

**Comment by theOehrly** [comment]
Closed in #306 by @SpyrosKoun
