### ISSUE TITLE
[BUG] Error when importing car data

### ISSUE THREAD

**Issue by tarik-boumaza** [theOehrly/Fast-F1#298]
### Describe the issue:

I wanted to import telemetries from FP1 of the 2022 Australian GP. I got an error for car 20 (driver 'MAG') and only for car 20.

`fastf1` version: `2.3.0`

### Reproduce the code example:

```python
import fastf1 as ff1

ff1.Cache.enable_cache('./cache')

session = ff1.get_session(2022, 3, 1)
session.load()
session.laps.pick_driver('MAG').get_car_data()
```

### Error message:

```shell
KeyError                                  Traceback (most recent call last)
Cell In [1], line 7
      5 session = ff1.get_session(2022 , 3, 1)
      6 session.load()
----> 7 session.laps.pick_driver('MAG').get_car_data()

File ~/anaconda3/envs/py38-env/lib/python3.8/site-packages/fastf1/core.py:2014, in Laps.get_car_data(self, **kwargs)
   2012     raise ValueError("Cannot slice telemetry because self contains Laps of multiple drivers!")
   2013 drv_num = drv_num[0]
-> 2014 car_data = self.session.car_data[drv_num].slice_by_lap(self, **kwargs).reset_index(drop=True)
   2015 return car_data

KeyError: '20'
```

**Comment by theOehrly** [comment]
Hi, thank you for reporting this problem. After a bit of investigation, I found that this is not really a problem with FastF1, but the source data is simply incorrect. For this one session, the telemetry data of Magnussen's car is apparently listed as car number 9 which would be Mazepin. The lap timing and driver list correctly list Magnussen as the driver, though. And then you get this problem where FastF1 obviously cannot find the correct data.

There is also no easy work around for this because FastF1 drops the telemetry data of unknown cars while loading the data. This is because there are sometimes weird non-existent cars in the data additionally.
You could potentially directly call `api.get_car_data`. This function will return the full source data. And then you get the data for car number 9 from that. I haven't tried it but it should work, if you need the data.
