### ISSUE TITLE
[BUG] <Error with lap object from particular sessions>

### ISSUE THREAD

**Issue by unknownmarc** [theOehrly/Fast-F1#302]
### Describe the issue:

The code runs fine for some sessions this season(Bahrain, Abu Dhabi) but shows this error for others. Any solutions would be appreciated

### Reproduce the code example:

```python
race= ff1.get_session(2022,'Imola','Qualifying')
race.load(telemetry=True)
laps_data = race.load_laps()


# Take the unique list of drivers
drivers = laps_data['Driver'].unique()


top_speed=pd.DataFrame(dtype=float)
top_speed["Driver"]=drivers

#sets driver as an index name
top_speed.set_index('Driver',inplace=True)

#loop to find topspeed of each driver
for driver in drivers:
    filter_df=laps_data[laps_data["Driver"]==driver]
    laps_drv=laps_data.pick_driver((driver))
    laps_driver=laps_drv.pick_fastest().get_telemetry().add_distance()
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\marcs\PycharmProjects\f1progs\main.py", line 33, in <module>
    laps_driver=laps_drv.pick_fastest().get_telemetry().add_distance()
  File "C:\Users\marcs\PycharmProjects\f1progs\venv\lib\site-packages\fastf1\core.py", line 2369, in get_telemetry
    pos_data = self.get_pos_data(pad=1, pad_side='both')
  File "C:\Users\marcs\PycharmProjects\f1progs\venv\lib\site-packages\fastf1\core.py", line 2411, in get_pos_data
    pos_data = self.session.pos_data[self['DriverNumber']].slice_by_lap(self, **kwargs).reset_index(drop=True)
  File "C:\Users\marcs\PycharmProjects\f1progs\venv\lib\site-packages\pandas\core\generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Lap' object has no attribute 'session'
```

**Comment by theOehrly** [comment]
Hi, thank you for reporting this. Yes, this is a bug, but you will still get an error once I fix this. 

The underlying problem is, that Albon (in this specifc case) did not set a fast lap. Therefore, `.pick_fastest` returns an empty `Lap` object. This object is missing the `session` attribute. I'll fix that.
 
But you're code will still fail then, because you cannot get telemetry data for an empty lap object. 
It's worth considering, whether `.pick_fastest` should return None here. But this still won't fix the problem really. In the end, you won't be able to chain these function calls and expect them to never throw an error.
