### ISSUE TITLE
[ENH] Driver colors need to be updated

### ISSUE THREAD

**Issue by Casper-Guo** [theOehrly/Fast-F1#324]
### Proposed new feature or change:

The driver colors currently provided by `fastf1.plotting.DRIVER_COLORS` are not updated for the 2023 season. 

For example, Fernando Alonso: [#0090ff](https://www.atatus.com/tools/color-code-viewer#0090ff)

**Comment by Casper-Guo** [comment]
Many plotting functions dealing with driver names and three-letter codes must be updated to reflect driver movements and rookies. If the maintainer is satisfied with the color scheme, I can open a PR to refresh these records.

**Comment by oscr** [comment]
Not a maintainer but as a user I think this sounds like a good improvement. @theOehrly is very helpful with reviews and prs.

**Comment by Casper-Guo** [comment]
@oscr There are some discussions about this issue (and similar) in #218 and the proposal is to unify updating team/driver names & colors with Ergast. I have not looked at the newest PR that implements Ergast support so I am not sure about any further development. Just based on my knowledge of Ergast, I cannot think of any easy ways to reliably update the colors.

**Comment by theOehrly** [comment]
> @oscr There are some discussions about this issue (and similar) in #218 and the proposal is to unify updating team/driver names & colors with Ergast. I have not looked at the newest PR that implements Ergast support so I am not sure about any further development. Just based on my knowledge of Ergast, I cannot think of any easy ways to reliably update the colors.

This needs a quick fix and a long term fix. The long term fix will hopefully come with v3.0.0 but I'm behind on the original schedule, because I intended this to be done already, originally. I forgot that I need to fix this again with a new minor release for this season. 
A PR that simply updates all the values would be very welcome. Then I can publish a new patch release so that this is fixed until a better approach is implemented. 

And you are correct, colors are not available from Ergast. I'm hoping that the F1 API can give this information, but I need to investigate that first.
