### ISSUE TITLE
[ENH] Laps-picking function improvements

### ISSUE THREAD

**Issue by Casper-Guo** [theOehrly/Fast-F1#370]
### Proposed new feature or change:

Some ideas for improving `Laps` objects helper methods:

1. Given that there are both `pick_driver` and `pick_drivers` and the equivalent for team, there should be a `pick_laps` method in addition to the currently implemented `pick_lap`.
2. `pick_tyre` is more appropriately termed `pick_compound`. The former name may be considered for future deprecation.
3. `pick_not_deleted` may be useful for qualifying sessions.
4. `pick_track_status` should also implement "excludes" for the `how` argument.

**Comment by theOehrly** [comment]
>     1. Given that there are both `pick_driver` and `pick_drivers` and the equivalent for team, there should be a `pick_laps` method in addition to the currently implemented `pick_lap`.

Maybe it would be better to make `pick_lap` accept lists of values. Then do the same for `pick_driver` and deprecate `pick_drivers`?

>     2. `pick_tyre` is more appropriately termed `pick_compound`. The former name may be considered for future deprecation.
Yes, I agree. Should be renamed and deprecated at some point.

>     3. `pick_not_deleted` may be useful for qualifying sessions.
Yes.

>     4. `pick_track_status` should also implement "excludes" for the `how` argument.
Yes, good idea.

**Comment by Casper-Guo** [comment]
> Maybe it would be better to make pick_lap accept lists of values. Then do the same for pick_driver and deprecate pick_drivers?

I agree this is the way to go for all three (drivers, teams, laps).

Thanks for the feedback. I will find some time to work on these. How are deprecations handled in this repo?

**Comment by theOehrly** [comment]
> > Maybe it would be better to make pick_lap accept lists of values. Then do the same for pick_driver and deprecate pick_drivers?
> 
> I agree this is the way to go for all three (drivers, teams, laps).
> 
> Thanks for the feedback. I will find some time to work on these. How are deprecations handled in this repo?

The policy for the guranteed timeline is very short: https://docs.fastf1.dev/contributing/contributing.html#rules
Most other projects introduce deprecations on the next minor release and remove the feature on the next major release.
I chose this more radical approach, because in theory, the F1 API can change at any time, potentially making some immediate breaking changes necessary. 
But for something like this, add a FutureWarning informing users that this will be remove in a future release. I guess for something like this, I'll keep it until the next major release because there's no harm done.
