### ISSUE TITLE
[BUG] Telemetry data not available for recent sessions

### ISSUE THREAD

**Issue by pesaventofilippo** [theOehrly/Fast-F1#412]
### Describe the issue:

As of now (Austrian GP, FP1 finished an hour ago), for some reason only certain data points are available, but others are not.
For example, accessing session.results seems to work, but session.laps doesn't, and throws the `The data you are trying to access has not been loaded yet. See Session.load` error.

This is quite strange because it normally happens when a session has just finished and the data is not available yet, but this time obviously the session has finished and (some of?) the data is available.

Not sure if this is a FastF1 or F1 livetiming related problem, just wanted to mention it.

### Reproduce the code example:

```python
session = fastf1.get_session(2023, "Austria", "FP1")
session.load(laps=True, telemetry=True)
print(session.results) # works
print(session.laps) # error
```

### Error message:

```shell
fastf1.core.DataNotLoadedError: The data you are trying to access has not been loaded yet. See `Session.load`
```

**Comment by pesaventofilippo** [comment]
Update: There's no problems at all with the latest Qualifying session, but the problem remains with the FP1 session.
At this point I'd guess it's a problem with either F1 or how FastF1 "reads" session data from the F1 API, maybe because of FP1 being the only practice session in the weekend?

**Comment by harningle** [comment]
It seems to be working now. I guess it's on the livetiming side, maybe a longer-than-usual lag?

**Comment by theOehrly** [comment]
@pesaventofilippo @harningle 
Telemetry data is still unavailable, I think. But timing data should be accessible now. 
I wasn't able to check what the problem was yesterday. But I have heard that apparently they were slow to make the data available. So likely that was the issue.

For telemetry, position data is still unavailable and FastF1 currently isn't capable to process only car telemetry data then. I'll fix that at some point in the future.
