### ISSUE TITLE
[BUG] Distance to Driver Ahead Not Working From Pos or Telemetry

### ISSUE THREAD

**Issue by pauljefferson** [theOehrly/Fast-F1#430]
### Describe the issue:

Hi,

I'm not sure if this is a bug or maybe the documentation not being clear (hopefully it's not me being an idiot and embarrassing myself!) but when you attempt to run add_driver_ahead it only works when you load car data, not position or all telemetry.

In those circumstances it is returning a fixed distance for the whole lap and an empty column for the car ahead:
![image](https://github.com/theOehrly/Fast-F1/assets/6294474/4ad1449d-fae4-4723-bd9a-5d18c224a84d)

Thanks

Fast F1 version: 3.0.7
Python version: 3.9.1

### Reproduce the code example:

```python
import fastf1 as ff1

year = 2023
wknd = 'Miami'
ses = 'R'
driver = 'TSU'

session = ff1.get_session(year, wknd, ses)
weekend = session.event
session.load()

lap = session.laps.pick_driver(driver).pick_lap(5)

telemetry = lap.get_car_data() # This works
telemetry = lap.get_pos_data() # This doesn't work
telemetry = lap.get_telemetry() # This doesn't work
telemetry = telemetry.add_driver_ahead()
```

**Comment by theOehrly** [comment]
I think this is a mixture of unclear documentation and a bug. Position data only is not supported because the speed is required. But both of the others should work. (Although, calling ``add_driver_ahead`` after accessing data through ``get_telemetry`` is not recommended because that data already contains interpolated values.)

I don't have time to look at this right now, but I'll get back to it in one or two weeks.

**Comment by pauljefferson** [comment]
Thanks!
