### ISSUE TITLE
[ENH] Pick in laps and out laps

### ISSUE THREAD

**Issue by Casper-Guo** [theOehrly/Fast-F1#453]
### Proposed new feature or change:

Inspired by a need in #452 

There is a `pick_wo_box` method but the inverse of it is equally useful for analyzing in lap and out lap performances and understanding undercut effectiveness etc.

`pick_inlaps` and `pick_outlaps` may be good-to-haves. Alternatively, they can be implemented under the same function.

Both are pandas oneliners but so are many other pick functions.

**Comment by theOehrly** [comment]
I'm not so much against adding these, even if they are pandas oneliners. There's quite few people using FastF1 who seem to be fairly new to Python. And while the code itself is not complicated, figuring out what you need to check for can be complicated.
Additionally, you can make the argument that it improves readability of user code, because the oneliner checks for the existence of a timestamp. It may not be immediately obvious how that indicates an inlap or outlap.
Therefore, I think it's reasonable to add these.

I'm somewhat concerned about having to separate methods. Simply because you then need to merge the return values again, if you want to combine both. That's again not quite straight forward. Therefore, it might be better to have a single function that returns either one or both? What are your opinions on that?

**Comment by Casper-Guo** [comment]
> Simply because you then need to merge the return values again, if you want to combine both.

This sounds like a common use case and should be supported natively. I think this following function signature is good:

`pick_box(..., include_inlaps: bool=True, include_outlaps: bool=True)`

**Comment by pesaventofilippo** [comment]
> I'm somewhat concerned about having to separate methods. Simply because you then need to merge the return values again, if you want to combine both. That's again not quite straight forward. Therefore, it might be better to have a single function that returns either one or both? What are your opinions on that?

That's true, that's mainly why I wasn't sure about this change.

> `pick_box(..., include_inlaps: bool=True, include_outlaps: bool=True)`

In my opinion this isn't the best way, because you could set both parameters to False and then it would still be confusing to use. I think we could do something like `pick_track_status()`, so for example using `pick_box_laps(which: str)`, where `which` could be 'in', 'out', or 'both', and I guess 'both' being the default.

What do you think?

**Comment by Casper-Guo** [comment]
Good call. That's quite clever

**Comment by pesaventofilippo** [comment]
Just updated the PR with the new changes.
Maybe have a look at the docstring I wrote for it. There could be an ambiguity with the word 'both' for new users (does it mean only laps that are both in and out at the same time, or are they separate?)

I tried to explain it in a few words, let me know if you have better ideas.

**Comment by theOehrly** [comment]
@pesaventofilippo I think the docstring is good. It's clearly and sufficiently explained, in my opinion.

**Comment by Casper-Guo** [comment]
Implemented in #454
