### ISSUE TITLE
Found Possible New API Source

### ISSUE THREAD

**Issue by siddharth-tewari** [theOehrly/Fast-F1#47]
Hello, I found on the official F1 site that there is a link called http://api.formula1.com/v1/event-tracker . I am not much a developer and learned a little bit python in school so just posted if anyone finds it useful.

**Comment by siddharth-tewari** [comment]
@theOehrly Actually after opening this issue, I found 2 more which are https://ltss.fiaformula2.com/streaming/hubs for Formula 2 and ltss.fiaformula3.com/streaming/hubs for Formula 3.

**Comment by theOehrly** [comment]
Those streams might work in theory, yes. They seem to be using the signalr protocol, and it is likely that they use the same backend and therefore have the same data format. But I haven't checked. 
The problem is that FastF1 has some hard coded references for F1 weekend schedules and so on. This is where the real difficulty might be in terms of supporting F2/F3. I'll keep it in mind, and maybe I can look into it at some point.

**Comment by siddharth-tewari** [comment]
@theOehrly Reopening the issue as having some doubts. How do use authenticate the http://api.formula1.com/v1/event-tracker api? Do we need to use our F1 account? Any code as I don't know anything about api's. For finding pages like TeamRadio,jsonStream, how do I find it for https://ltss.fiaformula2.com/streaming/hubs. Any tutorial links for reference?

**Comment by theOehrly** [comment]
@siddharth-tewari 
I'm not sure if I ever tried authentication with the event tracker api endpoint from python. No, I don't have any code for it. But I guess you need to authenticate with your F1 account. I'm not sure, it's already some time ago that I took a look at it.
I also don't have any tutorials for this. And it's not a given that the F2/F3 backend is the same as the one for F1.

**Comment by siddharth-tewari** [comment]
@theOehrly I mean F2/F3 backend is almost same but not meant F1.

**Comment by siddharth-tewari** [comment]
@theOehrly Any way how you did it? I tried from python but failed. Also what is your username as we gave our Name and Surname not any username
