### ISSUE TITLE
[BUG] Incorrect data Las Vegas Race

### ISSUE THREAD

**Issue by manpean** [theOehrly/Fast-F1#482]
### Describe the issue:

The data in Las Vegas race is not correct, for example: laps only contains 5 laps for each driver

Maybe it is stiil to early to load the session...

### Reproduce the code example:

```python
session = fastf1.get_session(2023, 'Vegas', 'R')
session.load()
laps=session.laps
```

**Comment by Pablomgom** [comment]
Same issue, also we have 30 drivers on the session
['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81', '236', '237', '238', '239', '240', '241', '242', '243', '246', '247']

**Comment by theOehrly** [comment]
Apparently, there were some technical problems on F1's side of things during the race. The live timing data archive on their API contains bad data data due to that.

It looks like they have at least partially fixed that now. I have a total of 946 laps now. So you can try to clear your FastF1 cache and see if it works. 

I don't really have time to look closer at it now. Please comment whether everything is fine now or if there are still problems.

**Comment by manpean** [comment]
Now it is solved

I close the issue
