### ISSUE TITLE
[ENH] Asyncio fastf1

### ISSUE THREAD

**Issue by formulatimer** [theOehrly/Fast-F1#513]
### Proposed new feature or change:

Hi,

If FastF1 uses the asyncio library to load the data of the sessions, FastF1 will be much faster
The asyncio library is easy to implement. What are your thoughts? I could dedicate some time to building that

**Comment by theOehrly** [comment]
Hi, I'm aware of the asyncio and its advantages. But I do not agree that it would be a big advantage in FastF1.

- Addressing the first point that this would make FastF1 "much" faster. I ran the following example code with cProfile to get detailed statistics about function calls and time spent in individual functions.

  ```
  import fastf1
  session = fastf1.get_session(2023, 10, 'R')
  session.load()
  ```

  Without caching (i.e. loading the session for the first time), the total runtime is 24 sec on my machine. Of that, 6.6 sec (27%) are spent in the function ``requests.get``, so more or less blocked by IO. 
With caching enabled, the total runtime is 3.5 seconds. At most, a few milliseconds may still be spent on requests. I did not look at file system operations caused by reading from the local cache, but I will assume that their duration is negligible.

  So overall, let us very generously assume that the use of asyncio simply "removes" any IO related waiting time (of course it can't, but it's the best case scenario in favour of asyncio). 
In that case, we see a roughly 25% speed increase the very first time a session is loaded. On all subsequent runs, users already have an 85% speed increase due to FastF1's caching system and there will be no further improvement from using asyncio here. 
I do not consider this to be "much faster".

- Adressing the second point about ease of implementation. This is not necessarily true here either. You cannot simply run all requests that take place during ``Session.load`` in parallel currently. The reason is that the following data processing actually relies on other data to be available already, so the data cannot be processed in arbitrary order. Therefore, some refactoring of FastF1's data processing would be necessary as well. I am planning to do such refactoring and that might facilitate things like using asyncio. But this is not the goal of the refactoring. Until then, I don't think this would be easy to implement here.

Overall, this does not give too much of a benefit. But it is still a fairly significant change internally. I don't think this is really important or necessary currently.
