### ISSUE TITLE
Yaw rate / longitudinal accel / lateral accel available directly from API?

### ISSUE THREAD

**Issue by Djeeeeee** [theOehrly/Fast-F1#518]
### Proposed new feature or change:

Hello,
Would it be possible to make yaw rate, longitudinal acceleration and lateral acceleration directly available from the API?
Thanks,

**Comment by theOehrly** [comment]
Hi, this data isn't available directly from (server) API. That means it would need to be calculated from the data that we currently have. While this is theoretically possible, the data that we have isn't accurate/doesn't have a high enough resolution to actually do that. So, sadly, there's no way to add this data.

This was just recently asked already, and you can find a more detailed response here: #507

**Comment by Djeeeeee** [comment]
Ok understood, that makes sense.

I guess we could post the maths somewhere in here and people can decide to use it or not at their own risk.

**Comment by theOehrly** [comment]
> I guess we could post the maths somewhere in here and people can decide to use it or not at their own risk.

The problem is that there is no single "the maths". Do you use a forward, backward or central differencing scheme? Do you filter/smooth the data? If yes, what kind of filtering do you use? Do you use filtering before the differentiation, after it, or both? Every single of these decisions may reduce one problem at the cost of making another one worse. That's the problem here.
