### ISSUE TITLE
[BUG] empty string sent to utils.to_datetime

### ISSUE THREAD

**Issue by Casper-Guo** [theOehrly/Fast-F1#526]
### Describe the issue:

Calling `get_event_schedule` causes the empty string to be sent to `utils.datetime`. The exception is handled but it shows up in the log.

### Reproduce the code example:

```python
import logging
import fastf1 as f

logging.basicConfig(
    level=logging.INFO, format="%(levelname)s\t%(filename)s\t%(message)s"
)

f.get_event_schedule(2024)
```

### Error message:

```shell
DEBUG   utils.py        Failed to parse datetime string ''
Traceback (most recent call last):
  File "/home/robery/.local/lib/python3.11/site-packages/fastf1/utils.py", line 208, in to_datetime
    date, time = x.strip('Z').split('T')
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
DEBUG   utils.py        Failed to parse datetime string ''
Traceback (most recent call last):
  File "/home/robery/.local/lib/python3.11/site-packages/fastf1/utils.py", line 208, in to_datetime
    date, time = x.strip('Z').split('T')
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by theOehrly** [comment]
I'm confused by this. First, I'm unable to reproduce this problem. This is probably because the missing times have all been added to the schedule over the last two week. That would mean, the issues are no longer occurring at the moment?

Second, the message is only logged with level DEBUG. But the example above configures logging to show the INFO level (and higher). So it shouldn't have been shown. I suppose that is a simple mistake in the code example?

**Comment by Casper-Guo** [comment]
You are right. I just tried the script again on my device and in a clean environment on a remote server and both ran without issues. Probably was a temporary issue when the schedule backend was outdated.
