### ISSUE TITLE
.get_session() fails for sessions which are not cached

### ISSUE THREAD

**Issue by sherrybecks** [theOehrly/Fast-F1#54]
Does this have anything to do with me using VPN? Thank you!
![QQ截图20211027015224](https://user-images.githubusercontent.com/93217668/138933909-d0127829-de03-48f2-b33f-a35e9fa64fe9.jpg)

**Comment by Talal26** [comment]
![image](https://user-images.githubusercontent.com/84981235/139560933-db955ea1-98d4-432e-8a96-f28ac83e2903.png)
Not working for me in the past 2 days.

**Comment by theOehrly** [comment]
The problem now exists for me too. Like the error message says, it is related to the Ergast API ([https://ergast.com/mrd/](https://ergast.com/mrd/)). Data from this API is currently required so that FastF1 can function at all. (The exception are sessions which you have previously loaded and which cached)

I do have a clue as to what the problem is and how to potentially work around it. Still, I have decided to contact the administrator of Ergast before implementing any workarounds on my side.
I'm working on solving this as soon as possible.

**Comment by theOehrly** [comment]
The problem has been fixed for now. You need to update to the latest version 2.1.10 of FastF1.

If you're interested, here's the explanation for what caused this problem.
After discussing the issue with the admin of Ergast, it looks like FastF1 got blocked from accessing Ergast in an attempt to stop a (maybe unintentional) DDoS attack against Ergast. But it seems like FastF1 was not the actual culprit and instead just blocked as collateral damage.
After discussing the problem, FastF1 will now use a custom user agent to identify itself. This will unblock access again and will allow us to verify that the excess traffic was not caused by FastF1.
