### ISSUE TITLE
[BUG] Error loading LiveData

### ISSUE THREAD

**Issue by nicZox** [theOehrly/Fast-F1#542]
### Describe the issue:

By loading the data recorded by livetiming, drivers are not found (being None) and making it impossible to use the functionality of FastF1

### Reproduce the code example:

```python
livedata = LiveTimingData('2024_Livetiming.txt')
session = fastf1.get_session(2024, 'Bahrain Grand Prix', 'R')
session.load(livedata=livedata)
```

### Error message:

```shell
req            INFO 	No cached data found for session_info. Loading data...
data           INFO 	Reading live timing data from recording. This may take a bit.
data          ERROR 	Error while trying to set correct session start date!
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Loading driver list
req            INFO 	Data has been written to cache!
core        WARNING 	Session results contain duplicate entries for driver(s) [None, None, None, None, None, None, None, None, None, None, None, None, None]
```

**Comment by nicZox** [comment]
@theOehrly Is there a possible bypass for this? Without waiting for 3.4.1?

**Comment by theOehrly** [comment]
> @theOehrly Is there a possible bypass for this? Without waiting for 3.4.1?

I don't know at the moment. I haven't investigated this in depth. I was simply able to reproduce the problem and it clearly looks like a bug.
Is there any particular reason why this is important? At the moment, all sessions (including pre-season testing) are available using the "normal" way of downloading the data from the API. Therefore, it's not really that important (short term) because only the fallback method is broken. Or is there something that particularly requires the usage of the recorded live data?
