### ISSUE TITLE
[BUG] Missing data in 2024 Sprint Qualifying

### ISSUE THREAD

**Issue by babi00** [theOehrly/Fast-F1#597]
### Describe the issue:

In 2024 Sprint Qualifying Sessions Q1, Q2 and Q3 times are missing. Could you please add them?

### Reproduce the code example:

```python
session=fastf1.get_session(2024,"Miami","Sprint Qualifying")
session.load()
session.results
```

**Comment by Casper-Guo** [comment]
See if this does what you want: [split_qualifying_sessions](https://docs.fastf1.dev/core.html#fastf1.core.Laps.split_qualifying_sessions)

**Comment by babi00** [comment]
> See if this does what you want: [split_qualifying_sessions](https://docs.fastf1.dev/core.html#fastf1.core.Laps.split_qualifying_sessions)

No, I meant that session.results["Q1"] (the same goes for Q2 and Q3) are filled with NaT values intead of the actual qualifying times (as it is, for example, in the qualifying session from fastf1.get_session(2024,"Miami","Q")

**Comment by theOehrly** [comment]
@babi00 please make sure you are using the latest version of FastF1. If you are using pip, run ``pip install --upgrade fastf1`` to update.
This should no longer be an issue in the most recent version.

**Comment by babi00** [comment]
> @babi00 please make sure you are using the latest version of FastF1. If you are using pip, run `pip install --upgrade fastf1` to update. This should no longer be an issue in the most recent version.

It says that I already have the latest version (3.3.7, right?). I don't understand if somehow it's just a problem for me or if it is a data's issue.

**Comment by theOehrly** [comment]
@babi00 I am currently on vacation without any  computer. So I cannot diagnose really. You can try and delete the whole content of the cache directory. FastF1 should print the path to your cache folder every time you run any script. Maybe this resolves the problem. Else, I can't help you any more before next week.

**Comment by MyosotisLz** [comment]
This is most likely related to #364 as Ergast as of now does not support both sprint shootout (2023) and sprint qualifying results.

Code example:
session=fastf1.get_session(2024,"Miami","Sprint Qualifying")
session.load()
print(session.results)

Output:
![image](https://github.com/theOehrly/Fast-F1/assets/117034849/60428765-8b8b-4683-9a66-feb93f5d970d)

**Comment by theOehrly** [comment]
@MyosotisLz is correct that Ergast does not support the Sprint Qualifying. But a large part of the data (including the Q1/2/3 times) should be calculated from the timing data as a fallback.

There was a problem where the renamed "Sprint Qualifying" this year wasn't correctly handled as a session that has qualifying format. There is/was a naming conflict because "Sprint Qualifying" already existed in 2021, but back then it was a session with race format. I've fixed this now to properly differentiate by year, and now the results will be available via the fallback mechanism.

**Comment by babi00** [comment]
> @MyosotisLz is correct that Ergast does not support the Sprint Qualifying. But a large part of the data (including the Q1/2/3 times) should be calculated from the timing data as a fallback.
> 
> There was a problem where the renamed "Sprint Qualifying" this year wasn't correctly handled as a session that has qualifying format. There is/was a naming conflict because "Sprint Qualifying" already existed in 2021, but back then it was a session with race format. I've fixed this now to properly differentiate by year, and now the results will be available via the fallback mechanism.

I'm sorry but I don't understand how can I can now access to Q1/Q2/Q3 times. I've installed the upgraded version but still didn't find a way. What do you mean with "fallback mechanism"?

**Comment by theOehrly** [comment]
@babi00 you don't need to do anything. If you have updated to v3.3.8, the Q1/2/3 times are now simply available in the results.

The fallback is just an internal thing that you don't need to worry about. I just wanted to mention it because obviously the data in question is not available on Ergast for this session.
