### ISSUE TITLE
[BUG] Failed to load schedule from FastF1 backend

### ISSUE THREAD

**Issue by formulatimer** [theOehrly/Fast-F1#617]
### Describe the issue:

logger      WARNING 	Failed to load schedule from FastF1 backend!

Ergast was not working this week but now is working and the error persists

### Reproduce the code example:

```python
import fastf1 as ff1
Location = ff1.get_event_schedule(2024).Location.iloc[1:]
```

### Error message:

```shell
logger      WARNING 	Failed to load schedule from FastF1 backend!
```

**Comment by theOehrly** [comment]
The "FastF1 backend" is independent of Ergast. Actually, it's just a bunch of JSON files in a different repository so that I don't need to bother with proper hosting 😅

Have you upgraded to a newer Python version recently? I have only seen this issue when switching between Python versions but using the same cache directory. Some differing dependency version can cause the HTTP cache to not work correctly then. This should be fixable by deleting the cache directory (or at least the "fastf1_http_cache.sqlite" file inside the cache directory).

**Comment by formulatimer** [comment]
I delete "fastf1_http_cache.sqlite" file and now it works properly Thamks!!
