### ISSUE TITLE
[ENH] Session load cache wiithout Ergast and F1 Livetiming API

### ISSUE THREAD

**Issue by formulatimer** [theOehrly/Fast-F1#622]
### Proposed new feature or change:

When the Ergast and F1 Livetiming APIs experience issues (which happens frequently with Ergast), the loading times can be very high or result in errors.

If you have stored the data in cache, you can avoid relying on the Ergast and F1 Livetiming APIs. This allows the session to load almost instantly, requiring only a quick check.

**Comment by theOehrly** [comment]
This already kind of exist, although you need to enable it manually:

https://docs.fastf1.dev/fastf1.html#fastf1.Cache.offline_mode

Apart from that, I'll be enabling a five second read timeout for Ergast requests in the next release.

This all wouldn't be a problem if the server responded with an error. But it often just doesn't respond at all which is why the requests take so long. The request timeout should improve this considerably.

**Comment by demrebicer** [comment]
Hello,

The Ergast API has been crashing a lot recently, and it is currently down as I am writing this message. A 5-second timeout would really solve many of my issues. @theOehrly  Do you have an estimated time for the next release? When do you plan to publish it?

**Comment by theOehrly** [comment]
@demrebicer I was trying to get the release done this morning. But my internet provider decided that I did not need internet. So I couldn't do anything. I'll try again this evening. 

But Ergast and F1 having API problems makes things more complicated for me too. So I am not entirely sure if I get it done. But I think that i should have workarounds for everything.

**Comment by demrebicer** [comment]
@theOehrly I have an idea for an improvement. Ergast allows downloading its database directly from their site. We could add a feature to the Fastf1 library to utilize this database. 

For those who do not wish to use the Ergast API, they could integrate the downloaded database file into their projects and provide the file path to Fastf1. Instead of making API requests, Fastf1 could fetch data from the database using SQL queries.

In the future, if Ergast shuts down completely, this database file could be hosted on a CDN, allowing users to retrieve the data from there.

**Comment by theOehrly** [comment]
@demrebicer adding SQL queries to the database file as a fallback for Ergast would be a major new feature. That's quite a bit of work if it should be done cleanly. There's basically no carry-over code from requesting data from the server to querying the database. I really don't want to do that 😅

Apart from that, when Ergast shuts down completely in 2025, the new successor API with a completely rewritten server will be up and running and we should have way less downtime and problems.

**Comment by theOehrly** [comment]
The new release is out and the five-second read timeout for Ergast has been added. "New Ergast" should be more reliable in a few months. 

A fallback for the current issues with the livetiming API has also been implemented.

Apart from that, Ergast is currently offline that much because someone is bombarding the server with a very high number of requests and varying users agents from multiple IP addresses. Mitigations have apparently been attempted, but it still puts load on the server and the current admin simply doesn't have endless time to deal with the problem.
