### ISSUE TITLE
[BUG] Session Data Loading for Race but Not Qualifying

### ISSUE THREAD

**Issue by AnthonyDalke** [theOehrly/Fast-F1#636]
### Describe the issue:

Hi!

First of all, thank you for this wonderful resource you've created! I leveraged it for a personal project to practice various data and software engineering skills (branch with the project in question [here](https://github.com/AnthonyDalke/f1data/tree/piastri), in case you want fuller context).

At a high level, it consists of an ETL process that loops through the rounds in each year within a year range I specify with environment variables and calls `.get_session()` to retrieve the qualifying and race data for each round. It then performs a series of transformations to shape the data and load it into a series of tables I intend to query for an analysis.

I've noticed some rounds fail to return full data. The issue appears to stem from `.get_session()` fetching records for the race but not the qualifying session. I've pulled out the relevant snippets of the code, but to provide an example, when I pull the 2000 season, it returns data for both the race and qualifying for the first round but not the second. Hopefully, the error message I've provided captures the necessary context.

Please don't hesitate to ask if additional information would help, and thank you, again, for what you do!

### Reproduce the code example:

```python
import fastf1 as ff1
ff1.set_log_level("DEBUG")

for year in list_years:
    ff1.Cache.clear_cache()
    for round in list_rounds:
        session = ff1.get_session(year, round, session)
        session.load()
```

### Error message:

```shell
_api          DEBUG     Falling back to livetiming mirror (https://livetiming-mirror.fastf1.dev)
logger      WARNING     Failed to load session info data!
logger        DEBUG     Traceback for failure in session info data
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fastf1/logger.py", line 151, in __wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fastf1/core.py", line 1448, in _load_session_info
    self._session_info = api.session_info(self.api_path,
  File "/usr/local/lib/python3.9/site-packages/fastf1/req.py", line 450, in _cached_api_request
    data = func(api_path, **func_kwargs)
  File "/usr/local/lib/python3.9/site-packages/fastf1/_api.py", line 1664, in session_info
    raise SessionNotAvailableError(
fastf1._api.SessionNotAvailableError: No data for this session! If this session only finished recently, please try again in a few minutes.
```

**Comment by Casper-Guo** [comment]
Can you determine the `year` and `round` combination that is causing the failure? Years prior to 2018 have less available data than 2018 onwards

**Comment by AnthonyDalke** [comment]
I’ve noticed it in multiple years. In the later years, such as 2005 and later, the missing data would often come through if I re-ran my script for only the affected rounds in a given year. However, that doesn’t seem to work for the earlier years.

**Comment by theOehrly** [comment]
I'm a bit short on time right now, but I just had a quick look at this.
The following is working fine for me:
```
.get_session(2000, 1, 'R')
.get_session(2000, 1, 'R')

**Comment by theOehrly** [comment]
I'm a bit short on time right now, but I just had a quick superficial look at this.

The following is working fine for me:

```
.get_session(2000, 1, 'R')
.get_session(2000, 1, 'Q')
.get_session(2000, 2, 'R')
```

The qualifying for the second round in 2000 is not working for me either. This is because the API from which FastF1 pulls the data is somehow missing data for this session. See https://ergast.com/api/f1/2000/2/qualifying vs https://ergast.com/api/f1/2000/1/qualifying

Regarding the error log/traceback you posted, it is not relevant here. In general, I don't recommend running FastF1 with the DEBUG log level enabled. It should not be shown by default. If it is, that would be a bug, probably. The messages there may be confusing and are not intended for users.
In this case, the error that is logged is completely expected for sessions before 2018. It is internally handled and only logged on the DEBUG level, but not raised. The expected output for these sessions should look like this:

```
>>> session.load()
core           INFO     Loading data for Brazilian Grand Prix - Race [v3.4.0]
req            INFO     No cached data found for session_info. Loading data...
_api           INFO     Fetching session info data...
logger      WARNING     Failed to load session info data!
core        WARNING     Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.
core           INFO     Finished loading data for 22 drivers: ['3', '11', '5', '6', '9', '10', '19', '18', '23', '21', '2', '8', '20', '1', '4', '7', '22', '14', '15', '12', '16', '17']
```

If you are having problems with more sessions, I need more detailed information which sessions those are.

**Comment by theOehrly** [comment]
> Regarding the logging, I actually had only set it at the DEBUG level based on what I saw in responses to seemingly related issues here on GitHub. I certainly can remove that.

I see, most people don't research that much, so this was unexpected. But did you then only copy a part of the output and skip the part after the error traceback? Because right now, your output looks like data loading did not finish properly.

All the sessions listed have the same problem. The data is missing in the upstream API. I have forward that information. But I cannot guarantee that this gets fixed any time soon. This is out of my hand.

**Comment by AnthonyDalke** [comment]
I understand, thank you very much for looking into it and getting back to me!
