### ISSUE TITLE
Problem plotting nGear Tuscan GP

### ISSUE THREAD

**Issue by TerminatorPlati** [theOehrly/Fast-F1#7]
With the data of the Tuscan GP, ​​the gears are represented as floats

![image](https://user-images.githubusercontent.com/69049717/92944582-75dbf100-f454-11ea-9588-a9c047092784.png)

**Comment by theOehrly** [comment]
Things like this will hopefully be fixed with v2.1 for this season. There's more effort made internally now for keeping data types consistent and reasonable, meaning gears should be an integer.
Although, matplotlib may still decide to show ticks intervals of .5, depending on scaling, range of data and so on

A pre-release for v2.1 is now available.
