### ISSUE TITLE
Missing sessions/Missing datas from Sprint Qualifying events

### ISSUE THREAD

**Issue by marinik98** [theOehrly/Fast-F1#77]
Hi, I'm building a GUI built around the fastf1 module and I've discovered that from every Sprint Qualifying event (Silverstone, Monza, Brazil) I can't quite access any session different from the race, don't know wheter I can import manually from Ergast those missing sessions or wheter I'm importing them wrong, already tried to update to the lastest version of the ff1 module, and already cleared the cached datas by command, by deleting the cache folder and recreating one.
If you want to try yourself ff1.get_session(2021, 'Monza', 'Q') should return this error
![Screenshot_20](https://user-images.githubusercontent.com/97163476/148204465-1e1717b6-4bb8-4fe2-a303-6967ebfe3e54.png)
.

**Comment by marinik98** [comment]
I have read the issue already solved, but the very last comment was that the command ff1.get_session(2021, 'Monza', 'Q') should now work, apparently the problem has come up again, I am going to force api cache to search for the session, but I don't think that with current version of the module there should still be this issue

**Comment by siddharth-tewari** [comment]
@marinik98 Use 'SQ' for Sprint Qualfying

**Comment by theOehrly** [comment]
@marinik98 This is not quite a straight forward problem as it seems. I just gave it a quick try and I worked just fine for me. 
Obviously you're using the latest version, so that is  fine.
This only happens on weekends with sprint qualifying?
I see that this exception originates from a TKinter callback. Can you confirm that the error also occurs when you just run a simple script with the following content

```
import fastf1 as ff1

ff1.get_session(2021, 'Monza', 'Q').load_laps()
```

**Comment by marinik98** [comment]
@theOehrly Weirdly enough it is not occuring when I run it as a simple script, neither when I run it with the cached data enabled, so it has something to do with tkinter integration?
