### ISSUE TITLE
[Question] Pick specific lap

### ISSUE THREAD

**Issue by hohondz** [theOehrly/Fast-F1#8]
Hi, I know I can use pick_fastest() to get lap with best LapTime, but is it posible to pick a specific lap (i.e Lap 10 from race). I want to see the speed of a specific lap of a certain driver. Thank you!

**Comment by theOehrly** [comment]
Yes, that's possible of course even if there is no convenient pick function. The laps class simply wraps a pandas DataFrame so all the usual pandas functionality for indexing is available.

What you can do for example is

```
session = fastf1.load_laps(....)  # whatever session you want to load
laps = session.load_laps()

laps_rus = laps.pick_driver('RUS')  # pick a driver
lap = laps_rus[laps_rus['LapNumber'] == 10].iloc[0]  # mind the ...iloc[0]
```

As noted above, you still need to append `.iloc[0]` because the previous expression will (usually) return a DataFrame with one row only. Of course, if lap 10 does not exist the dataframe will be empty and `.iloc[0]` will fail with an index error.

This allows you to pick laps based on data in any column.

**Comment by ImW1ll** [comment]
Hi, I tried what you proposed with `laps_rus = laps.pick_driver('RUS')  # pick a driver
lap = laps_rus[laps_rus['LapNumber'] == 10].iloc[0]  # mind the ...iloc[0]`. However, I get `Driver 241: Position data is incomplete!` each time. The script is connect to a Discord bot which spits out : AttributeError: 'Lap' object has no attribute 'session. 

I tried to implement your code as follow : 

` session.load()            
  laps_driver_1 = session.laps.pick_driver(str(arg4))
  laps_driver_2 = session.laps.pick_driver(str(arg6))

  lap_driver_1 = laps_driver_1[laps_driver_1[20] == 10].iloc[0]
  lap_driver_2 = laps_driver_2[laps_driver_2[20] == 10].iloc[0]
`

I'm still pretty new, what am I doing wrong?
Thanks!
